
FROM node:16.13.2 as build
WORKDIR /app

COPY ./yarn.lock ./
COPY ./package* ./
RUN yarn

COPY . .
RUN yarn build:prod

FROM node:16.13.2-alpine as run
WORKDIR /app

RUN yarn global add serve
COPY --from=build /app/build ./build

CMD ["serve", "-l", "80", "-s", "./build"]
